### ISSUE TITLE
DEPRECATION: The 'Program' visitor node is deprecated. Use 'Template' or 'Block' instead (node was 'Block')

### ISSUE THREAD

**Issue by boris-petrov** [mainmatter/ember-hbs-minifier#717]
I get lots of those warnings. I guess they come from [here](https://github.com/mainmatter/ember-hbs-minifier/blob/v1.2.0/hbs-minifier-plugin.js#L84). This started happening since Ember 5.9.

**Comment by NullVoxPopuli** [comment]
I also get a ton of these warnings, concluded the same

**Comment by NullVoxPopuli** [comment]
PR: https://github.com/mainmatter/ember-hbs-minifier/pull/720

Looks like I need to do some repo maintenance tho, as the dev node is 14...

**Comment by NullVoxPopuli** [comment]
figured out a way to fix the deprecation without a breaking change :tada: 

https://github.com/mainmatter/ember-hbs-minifier/pull/720/commits/9bda9e9e1b16c4139f8a953d546ee23434ba8725

**Comment by boris-petrov** [comment]
This has been fixed, thanks!
